### ISSUE TITLE
practica_matematicas_discretas_daniel_alejandro

### ISSUE THREAD

**Issue by DanAlejandr** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-DanAlejandr#1]
[practica_mate_discretas.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-DanAlejandr/files/12566736/practica_mate_discretas.pdf)

**Comment by 23620031** [comment]
PORTADA 25/25
PROCEDIMIENTO 25/25
FIGURAS ILUSTRACIONES Y FOTOGRAFÍAS 25/25
RESULTADOS Y CONCLUSIONES 25/25

CALIFICACIÓN 20/20

CALIFICADO POR EQUIPO DE "LÓPEZ DOMÍNGUEZ ISAÍAS BRAYAN"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
